colinsane: init at 325bf6e53514b8300a12e85d9dfc64e59c782cb6

diff --git a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
--- a/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
+++ b/repos/colinsane/pkgs/by-name/sane-scripts/src/sane-private-unlock-remote
@@ -4,11 +4,50 @@
 # unlock a remote private store by dropping the password in a discoverable place.
 # this only works if our own private store has been unlocked and this machine has access to the relevant secret.
 
-set -xeu
+set -eu
 
-host=$1
-passwd=$(sane-secrets-dump --field password "$host")
+usage() {
+  echo "sane-private-unlock-remote HOST"
+  echo "  ssh's into HOST and unlocks its encrypted data store (e.g. encrypted home directory)"
+  echo "  this is non-interactive, and only works so long as the machine running this script"
+  echo "  has HOST's key in its own keyring"
+}
 
-test -n "$passwd"
+host=
+parseArgs() {
+  while [ "$#" -ne 0 ]; do
+    local arg=$1
+    shift
+    case $arg in
+      (--help)
+        usage
+        exit 0
+        ;;
+      (*)
+        if [ -z "$host" ]; then
+          host=$arg
+        else
+          usage
+          exit 1
+        fi
+        ;;
+    esac
+  done
+}
 
-echo "$passwd" | ssh "$host" 'if ! test -f /mnt/persist/private/init; then cat /dev/stdin > /run/gocryptfs/private.key; fi'
+main() {
+  local host="$1"
+  local passwd=$(sane-secrets-dump --field password "$host")
+
+  if [ -z "$passwd" ]; then
+    echo "failed to decode password" | tee /dev/stderr
+    exit 1
+  fi
+
+  echo "attempting to mount private store on $host"
+  echo "$passwd" | timeout 30 ssh "$host" 'if ! test -f /mnt/persist/private/init; then cat /dev/stdin > /run/gocryptfs/private.key; fi'
+  echo "mount succeeded"
+}
+
+parseArgs "$@"
+main "$host"
diff --git a/repos/colinsane/scripts/check-uninsane b/repos/colinsane/scripts/check-uninsane
--- a/repos/colinsane/scripts/check-uninsane
+++ b/repos/colinsane/scripts/check-uninsane
@@ -5,7 +5,7 @@ echo "this script will check that uninsane.org is baseline operational"
 echo "it doesn't check all services, just the most critical ones"
 echo ""
 
-OVPNS_IPV4=185.157.162.178
+OVPNS_IPV4=156.146.51.235
 DOOF_IPV4=205.201.63.12
 
 usage() {
@@ -37,9 +37,9 @@ check() {
   local label=$1
   shift
   if [ "$verbose" -ge 1 ]; then
-    printf "checking %s (%s) \n" "$label" "$*"
+    printf "checking %s (%s)... " "$label" "$*"
   else
-    printf "checking %s\n" "$label"
+    printf "checking %s... " "$label"
   fi
   if [ "$verbose" -ge 2 ]; then
     "$@"
@@ -49,8 +49,10 @@ check() {
   local rc=$?
   if [ $rc -ne 0 ]; then
     last_error=$rc
-    printf "FAILED CHECK '%s'\n" "$label" >&2
+    printf "❌\n  FAILED CHECK '%s'\n" "$label" >&2
     echo "  $@" >&2
+  else
+    printf "✅\n"
   fi
   return $rc
 }
@@ -77,6 +79,7 @@ parseArgs "$@"
 
 check "uninsane.org. DNS" nslookup uninsane.org.
 check "[1.1.1.1] uninsane.org. DNS" nslookup uninsane.org. 1.1.1.1
+check "[8.8.8.8] uninsane.org. DNS" nslookup uninsane.org. 8.8.8.8
 check "[DOOF] uninsane.org. DNS" nslookup uninsane.org. "$DOOF_IPV4"
 # OVPNS DNS is no longer used
 # check "[OVPNS] uninsane.org. DNS" nslookup uninsane.org. "$OVPNS_IPV4"
@@ -95,6 +98,12 @@ check "[DOOF] https://uninsane.org online" curl "--connect-to" "uninsane.org:443
 check "[DOOF] https://matrix.uninsane.org online" curl "--connect-to" "matrix.uninsane.org:443:$DOOF_IPV4:443" --silent --fail-with-body https://matrix.uninsane.org
 
 check "uninsane.org DMARC record" nslookup -querytype=TXT _dmarc.uninsane.org.
+_checkPtr() {
+  local fwd=$1
+  local rev=$2
+  nslookup "$fwd" | grep "name = $rev$"
+}
+check "mx.uninsane.org PTR" _checkPtr "$OVPNS_IPV4" mx.uninsane.org.
 
 check "servo-hn wireguard network" ping -c 1 -W 3 servo-hn
 
@@ -136,6 +145,8 @@ _bitcoindSynchronized() {
 }
 check "Bitcoind synchronized" _bitcoindSynchronized
 check "Bitcoin Lightning" runOnHost servo clightning-sane status
+
+check "/mnt/persist/private" runOnHost servo systemctl status gocryptfs-private.service
 
 echo ""
 echo "systemctl --failed:"
diff --git a/repos/colinsane/scripts/update b/repos/colinsane/scripts/update
--- a/repos/colinsane/scripts/update
+++ b/repos/colinsane/scripts/update
@@ -1,7 +1,12 @@
 #!/usr/bin/env nix-shell
-#!nix-shell -i bash -p findutils -p nix-update
+#!nix-shell -i bash -p findutils -p git -p nix-update
 
-NIX_FILES_TOP=/home/colin/nixos
+# each update job has to do an entire nix eval, which can be memory intensive; be careful when tuning this.
+# N.B.: not all update jobs are atomic; parallel updates _may_ cause failed updates if eval of some package `pkgFoo`
+# depends on the `src` field of some library `libBar`, and the two are updated simultaneously.
+# this typically only happens when `libBar` is nix code, and `import`'d.
+PARALLELISM=8
+SELF_PATH=$PWD/$0
 
 usage() {
   echo "update: update rev/hash for one or more packages"
@@ -10,6 +15,7 @@ usage() {
   echo "options:"
   echo "- --dry-run"
   echo "- --verbose"
+  echo "- -j <n>  (default: $PARALLELISM)"
   echo ""
   echo "examples:"
   echo "- update nixpkgs: update only the nixpkgs input"
@@ -38,6 +44,14 @@ hasEffect() {
   fi
 }
 
+REPO_ROOT=
+repo_root() {
+  if [ -z "$REPO_ROOT" ]; then
+    REPO_ROOT=$(git -C "$(dirname SELF_PATH)" rev-parse --show-toplevel)
+  fi
+  echo "$REPO_ROOT"
+}
+
 # usage: getPkgs outVar prefix
 getPkgs() {
   local -n attrsArr="$1"
@@ -50,10 +64,10 @@ getPkgs() {
   # # but since i use Import From Derivation along paths which i also want to query,
   # # then i need to ensure those derivations are available for import.
   # debug "creating requisite .drv store paths"
-  # nix-instantiate -A nix "$NIX_FILES_TOP"
-  # nix-instantiate -A nixpkgs-bootstrap.master "$NIX_FILES_TOP"
+  # nix-instantiate -A nix "$(repo_root)"
+  # nix-instantiate -A nixpkgs-bootstrap.master "$(repo_root)"
   debug "querying packages to update as part of '$attrPrefix'"
-  local attrs=$(nix eval --raw -f "$NIX_FILES_TOP" 'updateTargets."'"$attrPrefix"'"' --apply 'builtins.concatStringsSep " "' "${nixFlags[@]}")
+  local attrs=$(nix eval --raw -f "$(repo_root)" 'updateTargets."'"$attrPrefix"'"' --apply 'builtins.concatStringsSep " "' "${nixFlags[@]}")
   debug "got: $attrs"
   attrsArr+=($attrs)
 }
@@ -61,29 +75,40 @@ getPkgs() {
 updateOnePkg() {
   local attrPath="$1"
 
-  local updateScript=$(nix eval --raw -f "$NIX_FILES_TOP" 'updateScripts."'"$attrPath"'"' "${nixFlags[@]}")
+  local updateScript=$(nix eval --raw -f "$(repo_root)" 'updateScripts."'"$attrPath"'"' "${nixFlags[@]}")
   if [ -z "$updateScript" ]; then
     warn "don't know how to update '$attrPath'"
     return
   fi
 
   # make sure everything needed to invoke the update script exists in-store
-  local context=$(nix eval --raw -f "$NIX_FILES_TOP" 'updateScripts."'"$attrPath"'"' --apply 's: builtins.concatStringsSep " " (builtins.attrNames (builtins.getContext s))' "${nixFlags[@]}")
+  local context=$(nix eval --raw -f "$(repo_root)" 'updateScripts."'"$attrPath"'"' --apply 's: builtins.concatStringsSep " " (builtins.attrNames (builtins.getContext s))' "${nixFlags[@]}")
   for c in $context; do
     debug "realizing updateScript requisite: $context"
     nix-store --realize "$c" "${nixFlags[@]}" || true
   done
 
+  local workingDir="$(repo_root)/.working/update/$attrPath"
+  rm -rf "$workingDir"
+  mkdir -p "$workingDir"
+
   info "updating: '$attrPath'"
+  info "working out of $workingDir"
   debug "$updateScript"
-  "$updateScript"
+
+  # update scripts often write artifacts (e.g. `git-commits.txt`) to the working directory,
+  # so change to a unique directory before running the update script to avoid interfering with any other
+  # update scripts that might be running simultaneously.
+  pushd "$workingDir"
+    "$updateScript" > >(tee update.log)  2> >(tee update.stderr >&2)
+  popd
 }
 
 updatePkgsInParallel() {
   debug "updating packages in parallel using xargs"
   debug "- $@"
-  debug "- xargs -n 1 -P 4 $0 ${scriptFlags[*]}"
-  echo "$@" | xargs -n 1 -P 4 "$0" "${scriptFlags[@]}"
+  debug "- xargs -n 1 -P $PARALLELISM $0 ${scriptFlags[*]}"
+  echo "$@" | xargs -n 1 -P "$PARALLELISM" "$0" "${scriptFlags[@]}"
 }
 
 scriptFlags=()
@@ -106,6 +131,10 @@ parseArgs() {
       (--verbose)
         scriptFlags+=(--verbose)
         verbose=1
+        ;;
+      (-j)
+        PARALLELISM=$1
+        shift
         ;;
       (--*)
         nixFlags+=("$arg")
