colinsane: init at 08a9b838e59c3ea562df3a448051ed25b71a20af

diff --git a/repos/colinsane/hosts/common/programs/sane-input-handler/sane-input-handler b/repos/colinsane/hosts/common/programs/sane-input-handler/sane-input-handler
--- a/repos/colinsane/hosts/common/programs/sane-input-handler/sane-input-handler
+++ b/repos/colinsane/hosts/common/programs/sane-input-handler/sane-input-handler
@@ -1,5 +1,5 @@
 #!/usr/bin/env nix-shell
-#!nix-shell -i bash -p coreutils -p killall -p playerctl -p procps -p sane-open-desktop -p sway -p util-linux -p wireplumber
+#!nix-shell -i bash -p coreutils -p jq -p killall -p playerctl -p procps -p sane-open -p sway -p util-linux -p wireplumber
 
 # input map considerations
 # - using compound actions causes delays.
@@ -12,8 +12,8 @@
 #
 # example of a design which considers these things:
 # - when unlocked:
-#   - volup tap       -> app menu
-#   - volup hold      -> file browser
+#   - volup tap       -> file browser
+#   - volup hold      -> app menu
 #   - voldown press   -> keyboard
 #   - voldown hold    -> terminal
 #   - power x2        -> screenoff
@@ -60,6 +60,12 @@ KEYBOARD="${KEYBOARD:-wvkbd-mobintl}"
 
 action="$1"
 
+log() {
+  printf "sane-input-handler: %s\n" "$1"
+}
+
+## HELPERS
+
 isTouchOn() {
   # success if all touch inputs have their events enabled
   swaymsg -t get_inputs --raw \
@@ -81,7 +87,23 @@ isInhibited() {
   pidof rofi
 }
 
+handleWith() {
+  local state=
+  if [ -n "$_isInhibited" ]; then
+    state="inhibited+"
+  fi
+  if [ -n "$_isAllOn" ]; then
+    state="${state}on"
+  else
+    state="${state}off"
+  fi
+  log "state=$state action=$action: handleWith: $*"
+  "$@"
+  exit $?
+}
 
+
+## HANDLERS
 ignore() {
   true
 }
@@ -102,26 +124,17 @@ allOff() {
 }
 
 toggleKeyboard() {
-  local kbpid=$(pidof "$KEYBOARD")
-  if [ -z "$kbpid" ] || ! ( env kill -s RTMIN+0 "$kbpid" ); then
-    echo "sane-input-handler: failed to toggle keyboard: $KEYBOARD"
+  local keyboardPid=$(pidof "$KEYBOARD")
+  if [ -z "$keyboardPid" ]; then
+    log "cannot find $KEYBOARD"
+    return
   fi
+
+  # `env` so that we get the right `kill` binary instead of bash's builtin
+  env kill -s RTMIN+0 "$keyboardPid"
 }
 
-handleWith() {
-  state=
-  if [ -n "$_isInhibited" ]; then
-    state="inhibited+"
-  fi
-  if [ -n "$_isAllOn" ]; then
-    state="${state}on"
-  else
-    state="${state}off"
-  fi
-  echo "sane-input-handler: state=$state action=$action: handleWith: $@"
-  "$@"
-  exit 0
-}
+## DISPATCHERS
 
 dispatchDefault() {
   case "$action" in
@@ -169,11 +182,11 @@ dispatchOn() {
       ;;
     "power_and_volup")
       # power (hold) -> volup: take screenshot
-      handleWith sane-open-desktop sane-screenshot.desktop
+      handleWith sane-open --application sane-screenshot.desktop
       ;;
     "power_and_voldown")
       # power (hold) -> voldown: open camera
-      handleWith sane-open-desktop org.postmarketos.Megapixels.desktop
+      handleWith sane-open --auto-keyboard --application org.postmarketos.Megapixels.desktop
       ;;
     "power_then_volup")
       # power (tap) -> volup: rotate CCW
@@ -185,12 +198,14 @@ dispatchOn() {
       ;;
 
     "volup_tap_1")
-      # volume up once: system menu
-      handleWith sane-open-desktop rofi.desktop
+      # volume up once: filesystem browser
+      handleWith sane-open --auto-keyboard --application rofi-filebrowser.desktop
       ;;
     "volup_hold_1")
-      # volume up hold: just browse files
-      handleWith sane-open-desktop rofi-filebrowser.desktop
+      # volume up hold: browse files and apps
+      # reset fs directory: useful in case you get stuck in broken directory (e.g. one which lacks a `..` entry)
+      rm -f ~/.cache/rofi/rofi3.filebrowsercache
+      handleWith sane-open --auto-keyboard --application rofi.desktop
       ;;
 
     "voldown_start")
@@ -200,7 +215,7 @@ dispatchOn() {
     "voldown_hold_1")
       # hold voldown to launch terminal
       # note we already triggered the keyboard; that's fine: usually keyboard + terminal go together :)
-      handleWith sane-open-desktop xdg-terminal-exec.desktop
+      handleWith sane-open --auto-keyboard --application xdg-terminal-exec.desktop
       ;;
     "voldown_tap_1")
       # swallow, to prevent keyboard from also triggering media controls
